<a href="https://colab.research.google.com/github/EricaRaujoData/EricaRaujoData/blob/master/analise_ambiental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importação do pacote pandas para tratamento e análise de dados
import pandas as pd

In [ ]:
#lendo o arquivo de banco de dados
df = pd.read_excel("/content/drive/MyDrive/Bases de Dados/(2) atlas_ambiental.xlsx")

In [ ]:
#visualizando as 5 primeiras linhas
df.head()

,cód_ibge,distritos,renda,quota,escolaridade,idade,mortalidade,txcresc,causasext,favel,denspop
0,1,Água Rasa,1961,34.62,7.6,32,13.86,-1.840000,52.98,0.00,125.61
1,2,Alto de Pinheiros,4180,75.96,8.4,33,8.68,-2.520000,38.57,0.69,57.56
2,3,Anhanguera,1093,4.50,5.8,23,15.36,18.120001,22.68,0.00,8.57
3,4,Aricanduva,1311,21.02,6.8,27,18.43,-1.070000,76.22,5.38,138.54
4,5,Artur Alvim,1248,15.91,7.0,27,19.73,-1.400000,67.25,4.11,167.40

In [ ]:
#trocando o nome dos títulos das colunas e atribuindo ao novo data frame (df)
df = df.rename(columns={"cód_ibge":"IBGE"})

In [ ]:
df.head()

,IBGE,distritos,renda,quota,escolaridade,idade,mortalidade,txcresc,causasext,favel,denspop
0,1,Água Rasa,1961,34.62,7.6,32,13.86,-1.840000,52.98,0.00,125.61
1,2,Alto de Pinheiros,4180,75.96,8.4,33,8.68,-2.520000,38.57,0.69,57.56
2,3,Anhanguera,1093,4.50,5.8,23,15.36,18.120001,22.68,0.00,8.57
3,4,Aricanduva,1311,21.02,6.8,27,18.43,-1.070000,76.22,5.38,138.54
4,5,Artur Alvim,1248,15.91,7.0,27,19.73,-1.400000,67.25,4.11,167.40

In [ ]:
#total de linhas e colunas BD
df.shape

(96, 11)

In [ ]:
#apresentando os tipos das métricas
df.dtypes

IBGE              int64
distritos        object
renda             int64
quota           float64
escolaridade    float64
idade             int64
mortalidade     float64
txcresc         float64
causasext       float64
favel           float64
denspop         float64
dtype: object

In [ ]:
#retornar as últimas linhas do dataframe
df.tail()

,IBGE,distritos,renda,quota,escolaridade,idade,mortalidade,txcresc,causasext,favel,denspop
91,92,Vila Medeiros,1405,19.76,6.8,27,15.43,-1.41,77.98,2.49,188.93
92,93,Vila Prudente,1755,32.08,7.2,30,14.36,-2.55,66.51,7.43,101.44
93,94,Vila Sônia,2970,41.41,7.4,27,16.76,-0.90,74.68,14.93,80.12
94,95,São Domingos,2047,23.51,6.8,26,14.30,0.71,62.35,8.55,72.92
95,96,Lajeado,775,8.49,5.4,21,18.65,2.83,103.32,3.84,141.01

In [ ]:
#gerar estatísticas descritivas do banco de dados
df.describe()

,IBGE,renda,quota,escolaridade,idade,mortalidade,txcresc,causasext,favel,denspop
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,48.500000,1856.218750,30.478021,7.075000,27.395833,15.992812,0.041146,71.086667,5.932188,99.860104
std,27.856777,970.774441,23.040243,1.008908,4.385332,4.994409,3.509652,23.315169,7.883763,49.606814
min,1.000000,159.000000,0.610000,4.800000,20.000000,6.460000,-6.240000,22.680000,0.000000,0.370000
25%,24.750000,1150.000000,12.400000,6.300000,23.000000,12.960000,-2.042500,56.417500,0.000000,64.317500
50%,48.500000,1628.000000,24.305000,7.000000,27.000000,16.230000,-0.835000,70.395000,3.015000,96.165000
75%,72.250000,2315.500000,40.990000,7.850000,31.000000,18.720000,1.342500,82.370000,7.837500,136.222500
max,96.000000,5146.000000,104.730000,9.200000,36.000000,44.250000,18.120001,127.370000,45.690000,249.600000

In [ ]:
#contar quantas linhas ou quantos casos e quantas colunas o banco de dados tem
df.shape

(96, 11)

In [ ]:
#apresentar o nome das colunas e/ou métricas
df.columns

Index(['IBGE', 'distritos', 'renda', 'quota', 'escolaridade', 'idade',
       'mortalidade', 'txcresc', 'causasext', 'favel', 'denspop'],
      dtype='object')

In [ ]:
#analisar registros únicos de idade
df["idade"].unique()

array([32, 33, 23, 27, 31, 30, 22, 29, 24, 26, 21, 35, 34, 36, 28, 20, 25])

In [ ]:
#selecionar apenas os casos do distrito de Aricanduva
Aricanduva = df.loc[df["distritos"] == "Aricanduva"]

,IBGE,distritos,renda,quota,escolaridade,idade,mortalidade,txcresc,causasext,favel,denspop
3,4,Aricanduva,1311,21.02,6.8,27,18.43,-1.07,76.22,5.38,138.54

In [ ]:
#retorna uma lista de valores únicos de "Aricanduva" encontrados na coluna
#"distritos" do DataFrame

array(['Aricanduva'], dtype=object)

In [ ]:
#agrupamento de dados - quantos distritos tem pessoas com cada idade?
df.groupby("idade")["distritos"].nunique()

idade
20     1
21     9
22     3
23    12
24     9
25     2
26     8
27     7
28     3
29     7
30     7
31     7
32     7
33     3
34     7
35     3
36     1
Name: distritos, dtype: int64

In [ ]:
#calcular a média dos valores da coluna mortalidade
df.groupby("distritos")["mortalidade"].mean()

distritos
Alto de Pinheiros     8.68
Anhanguera           15.36
Aricanduva           18.43
Artur Alvim          19.73
Barra Funda           8.62
                     ...
Vila Matilde         19.13
Vila Medeiros        15.43
Vila Prudente        14.36
Vila Sônia           16.76
Água Rasa            13.86
Name: mortalidade, Length: 96, dtype: float64